import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { catchError, Observable, of, ReplaySubject } from 'rxjs';
import { environment } from 'src/environments/environment';
import { DEFAULT_CITY_NAME } from '../constants';
import { ICurrentWeatherApiResponse } from '../models/current-weather-api-response.model';
import { ICurrentWeather } from '../models/current-weather.model';
import { IForecastApiResponse } from '../models/forecast-api-response.model';
import { IFullDailyForecast } from '../models/daily-forecast.model';

const response = {
  "location": {
    "name": "London", "region": "City of London, Greater London", "country": "United Kingdom", "lat": 51.52, "lon": -0.11, "tz_id": "Europe/London", "localtime_epoch": 1643026236, "localtime": "2022-01-24 12:10"
  },
  "current": {
    "last_updated_epoch": 1643022000, "last_updated": "2022-01-24 11:00", "temp_c": 4.0, "temp_f": 39.2, "is_day": 1, "condition": { "text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png", "code": 1009 }, "wind_mph": 4.3, "wind_kph": 6.8, "wind_degree": 90, "wind_dir": "E", "pressure_mb": 1034.0, "pressure_in": 30.53, "precip_mm": 0.0, "precip_in": 0.0, "humidity": 81, "cloud": 75, "feelslike_c": 3.2, "feelslike_f": 37.8, "vis_km": 10.0, "vis_miles": 6.0, "uv": 3.0, "gust_mph": 3.1, "gust_kph": 5.0
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-01-24",
        "date_epoch": 1642982400,
        "day": {
          "maxtemp_c": 9.4,
          "maxtemp_f": 48.9,
          "mintemp_c": 2.6,
          "mintemp_f": 36.7,
          "avgtemp_c": 5.5,
          "avgtemp_f": 41.9,
          "maxwind_mph": 3.6,
          "maxwind_kph": 5.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 78,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "07:50 AM",
          "sunset": "04:35 PM",
          "moonrise": "No moonrise",
          "moonset": "10:39 AM",
          "moon_phase": "Last Quarter",
          "moon_illumination": "49"
        }, "hour": [
          {
            "time_epoch": 1642982400,
            "time": "2022-01-24 00:00",
            "temp_c": 5.5,
            "temp_f": 41.9,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 160,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 96,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 5.5,
            "heatindex_f": 41.9,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1642986000,
            "time": "2022-01-24 01:00",
            "temp_c": 5.3,
            "temp_f": 41.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 159,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 95,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.3,
            "heatindex_f": 41.5,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1642989600,
            "time": "2022-01-24 02:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 153,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 75,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 1
          },
          {
            "time_epoch": 1642993200,
            "time": "2022-01-24 03:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 139,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 64,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 1
          },
          {
            "time_epoch": 1642996800,
            "time": "2022-01-24 04:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 151,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 55,
            "feelslike_c": 2.9,
            "feelslike_f": 37.2,
            "windchill_c": 2.9,
            "windchill_f": 37.2,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643000400,
            "time": "2022-01-24 05:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 131,
            "wind_dir": "SE",
            "pressure_mb": 1032,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 42,
            "feelslike_c": 3,
            "feelslike_f": 37.4,
            "windchill_c": 3,
            "windchill_f": 37.4,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643004000,
            "time": "2022-01-24 06:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 36,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643007600,
            "time": "2022-01-24 07:00",
            "temp_c": 2.9,
            "temp_f": 37.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 129,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 34,
            "feelslike_c": 2,
            "feelslike_f": 35.6,
            "windchill_c": 2,
            "windchill_f": 35.6,
            "heatindex_c": 2.9,
            "heatindex_f": 37.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.7,
            "gust_kph": 7.6,
            "uv": 1
          },
          {
            "time_epoch": 1643011200,
            "time": "2022-01-24 08:00",
            "temp_c": 2.6,
            "temp_f": 36.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 14,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 2.6,
            "heatindex_f": 36.7,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 2
          },
          {
            "time_epoch": 1643014800,
            "time": "2022-01-24 09:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 96,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 7,
            "feelslike_c": 2.3,
            "feelslike_f": 36.1,
            "windchill_c": 2.3,
            "windchill_f": 36.1,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 2
          },
          {
            "time_epoch": 1643018400,
            "time": "2022-01-24 10:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 6,
            "feelslike_c": 3.6,
            "feelslike_f": 38.5,
            "windchill_c": 3.6,
            "windchill_f": 38.5,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 2
          },
          {
            "time_epoch": 1643022000,
            "time": "2022-01-24 11:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 1,
            "feelslike_c": 7.5,
            "feelslike_f": 45.5,
            "windchill_c": 7.5,
            "windchill_f": 45.5,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643025600,
            "time": "2022-01-24 12:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 0,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643029200,
            "time": "2022-01-24 13:00",
            "temp_c": 9.1,
            "temp_f": 48.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 0,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 9.1,
            "heatindex_f": 48.4,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 3
          },
          {
            "time_epoch": 1643032800,
            "time": "2022-01-24 14:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.1,
            "feelslike_f": 48.4,
            "windchill_c": 9.1,
            "windchill_f": 48.4,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643036400,
            "time": "2022-01-24 15:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.3,
            "feelslike_f": 48.7,
            "windchill_c": 9.3,
            "windchill_f": 48.7,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643040000,
            "time": "2022-01-24 16:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 0,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643043600,
            "time": "2022-01-24 17:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 0,
            "feelslike_c": 7.2,
            "feelslike_f": 45,
            "windchill_c": 7.2,
            "windchill_f": 45,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 1
          },
          {
            "time_epoch": 1643047200,
            "time": "2022-01-24 18:00",
            "temp_c": 7.3,
            "temp_f": 45.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 0,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 7.3,
            "heatindex_f": 45.1,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643050800,
            "time": "2022-01-24 19:00",
            "temp_c": 6.9,
            "temp_f": 44.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 0,
            "feelslike_c": 6.1,
            "feelslike_f": 43,
            "windchill_c": 6.1,
            "windchill_f": 43,
            "heatindex_c": 6.9,
            "heatindex_f": 44.4,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643054400,
            "time": "2022-01-24 20:00",
            "temp_c": 3.7,
            "temp_f": 38.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 83,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 5,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.7,
            "heatindex_f": 38.7,
            "dewpoint_c": 1.8,
            "dewpoint_f": 35.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1643058000,
            "time": "2022-01-24 21:00",
            "temp_c": 3.4,
            "temp_f": 38.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 10,
            "feelslike_c": 2.2,
            "feelslike_f": 36,
            "windchill_c": 2.2,
            "windchill_f": 36,
            "heatindex_c": 3.4,
            "heatindex_f": 38.1,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643061600,
            "time": "2022-01-24 22:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 92,
            "cloud": 15,
            "feelslike_c": 1.9,
            "feelslike_f": 35.4,
            "windchill_c": 1.9,
            "windchill_f": 35.4,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1
          },
          {
            "time_epoch": 1643065200,
            "time": "2022-01-24 23:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 93,
            "cloud": 19,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          }
        ]
      },{
        "date": "2022-01-24",
        "date_epoch": 1642982400,
        "day": {
          "maxtemp_c": 9.4,
          "maxtemp_f": 48.9,
          "mintemp_c": 2.6,
          "mintemp_f": 36.7,
          "avgtemp_c": 5.5,
          "avgtemp_f": 41.9,
          "maxwind_mph": 3.6,
          "maxwind_kph": 5.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 78,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "07:50 AM",
          "sunset": "04:35 PM",
          "moonrise": "No moonrise",
          "moonset": "10:39 AM",
          "moon_phase": "Last Quarter",
          "moon_illumination": "49"
        }, "hour": [
          {
            "time_epoch": 1642982400,
            "time": "2022-01-24 00:00",
            "temp_c": 5.5,
            "temp_f": 41.9,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 160,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 96,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 5.5,
            "heatindex_f": 41.9,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1642986000,
            "time": "2022-01-24 01:00",
            "temp_c": 5.3,
            "temp_f": 41.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 159,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 95,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.3,
            "heatindex_f": 41.5,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1642989600,
            "time": "2022-01-24 02:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 153,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 75,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 1
          },
          {
            "time_epoch": 1642993200,
            "time": "2022-01-24 03:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 139,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 64,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 1
          },
          {
            "time_epoch": 1642996800,
            "time": "2022-01-24 04:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 151,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 55,
            "feelslike_c": 2.9,
            "feelslike_f": 37.2,
            "windchill_c": 2.9,
            "windchill_f": 37.2,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643000400,
            "time": "2022-01-24 05:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 131,
            "wind_dir": "SE",
            "pressure_mb": 1032,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 42,
            "feelslike_c": 3,
            "feelslike_f": 37.4,
            "windchill_c": 3,
            "windchill_f": 37.4,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643004000,
            "time": "2022-01-24 06:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 36,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643007600,
            "time": "2022-01-24 07:00",
            "temp_c": 2.9,
            "temp_f": 37.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 129,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 34,
            "feelslike_c": 2,
            "feelslike_f": 35.6,
            "windchill_c": 2,
            "windchill_f": 35.6,
            "heatindex_c": 2.9,
            "heatindex_f": 37.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.7,
            "gust_kph": 7.6,
            "uv": 1
          },
          {
            "time_epoch": 1643011200,
            "time": "2022-01-24 08:00",
            "temp_c": 2.6,
            "temp_f": 36.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 14,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 2.6,
            "heatindex_f": 36.7,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 2
          },
          {
            "time_epoch": 1643014800,
            "time": "2022-01-24 09:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 96,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 7,
            "feelslike_c": 2.3,
            "feelslike_f": 36.1,
            "windchill_c": 2.3,
            "windchill_f": 36.1,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 2
          },
          {
            "time_epoch": 1643018400,
            "time": "2022-01-24 10:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 6,
            "feelslike_c": 3.6,
            "feelslike_f": 38.5,
            "windchill_c": 3.6,
            "windchill_f": 38.5,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 2
          },
          {
            "time_epoch": 1643022000,
            "time": "2022-01-24 11:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 1,
            "feelslike_c": 7.5,
            "feelslike_f": 45.5,
            "windchill_c": 7.5,
            "windchill_f": 45.5,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643025600,
            "time": "2022-01-24 12:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 0,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643029200,
            "time": "2022-01-24 13:00",
            "temp_c": 9.1,
            "temp_f": 48.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 0,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 9.1,
            "heatindex_f": 48.4,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 3
          },
          {
            "time_epoch": 1643032800,
            "time": "2022-01-24 14:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.1,
            "feelslike_f": 48.4,
            "windchill_c": 9.1,
            "windchill_f": 48.4,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643036400,
            "time": "2022-01-24 15:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.3,
            "feelslike_f": 48.7,
            "windchill_c": 9.3,
            "windchill_f": 48.7,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643040000,
            "time": "2022-01-24 16:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 0,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643043600,
            "time": "2022-01-24 17:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 0,
            "feelslike_c": 7.2,
            "feelslike_f": 45,
            "windchill_c": 7.2,
            "windchill_f": 45,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 1
          },
          {
            "time_epoch": 1643047200,
            "time": "2022-01-24 18:00",
            "temp_c": 7.3,
            "temp_f": 45.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 0,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 7.3,
            "heatindex_f": 45.1,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643050800,
            "time": "2022-01-24 19:00",
            "temp_c": 6.9,
            "temp_f": 44.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 0,
            "feelslike_c": 6.1,
            "feelslike_f": 43,
            "windchill_c": 6.1,
            "windchill_f": 43,
            "heatindex_c": 6.9,
            "heatindex_f": 44.4,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643054400,
            "time": "2022-01-24 20:00",
            "temp_c": 3.7,
            "temp_f": 38.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 83,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 5,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.7,
            "heatindex_f": 38.7,
            "dewpoint_c": 1.8,
            "dewpoint_f": 35.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1643058000,
            "time": "2022-01-24 21:00",
            "temp_c": 3.4,
            "temp_f": 38.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 10,
            "feelslike_c": 2.2,
            "feelslike_f": 36,
            "windchill_c": 2.2,
            "windchill_f": 36,
            "heatindex_c": 3.4,
            "heatindex_f": 38.1,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643061600,
            "time": "2022-01-24 22:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 92,
            "cloud": 15,
            "feelslike_c": 1.9,
            "feelslike_f": 35.4,
            "windchill_c": 1.9,
            "windchill_f": 35.4,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1
          },
          {
            "time_epoch": 1643065200,
            "time": "2022-01-24 23:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 93,
            "cloud": 19,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          }
        ]
      },{
        "date": "2022-01-24",
        "date_epoch": 1642982400,
        "day": {
          "maxtemp_c": 9.4,
          "maxtemp_f": 48.9,
          "mintemp_c": 2.6,
          "mintemp_f": 36.7,
          "avgtemp_c": 5.5,
          "avgtemp_f": 41.9,
          "maxwind_mph": 3.6,
          "maxwind_kph": 5.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 78,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "07:50 AM",
          "sunset": "04:35 PM",
          "moonrise": "No moonrise",
          "moonset": "10:39 AM",
          "moon_phase": "Last Quarter",
          "moon_illumination": "49"
        }, "hour": [
          {
            "time_epoch": 1642982400,
            "time": "2022-01-24 00:00",
            "temp_c": 5.5,
            "temp_f": 41.9,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 160,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 96,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 5.5,
            "heatindex_f": 41.9,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1642986000,
            "time": "2022-01-24 01:00",
            "temp_c": 5.3,
            "temp_f": 41.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 159,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 95,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.3,
            "heatindex_f": 41.5,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1642989600,
            "time": "2022-01-24 02:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 153,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 75,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 1
          },
          {
            "time_epoch": 1642993200,
            "time": "2022-01-24 03:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 139,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 64,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 1
          },
          {
            "time_epoch": 1642996800,
            "time": "2022-01-24 04:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 151,
            "wind_dir": "SSE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 55,
            "feelslike_c": 2.9,
            "feelslike_f": 37.2,
            "windchill_c": 2.9,
            "windchill_f": 37.2,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643000400,
            "time": "2022-01-24 05:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 131,
            "wind_dir": "SE",
            "pressure_mb": 1032,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 42,
            "feelslike_c": 3,
            "feelslike_f": 37.4,
            "windchill_c": 3,
            "windchill_f": 37.4,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643004000,
            "time": "2022-01-24 06:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.49,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 82,
            "cloud": 36,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1643007600,
            "time": "2022-01-24 07:00",
            "temp_c": 2.9,
            "temp_f": 37.2,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 129,
            "wind_dir": "SE",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 34,
            "feelslike_c": 2,
            "feelslike_f": 35.6,
            "windchill_c": 2,
            "windchill_f": 35.6,
            "heatindex_c": 2.9,
            "heatindex_f": 37.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.7,
            "gust_kph": 7.6,
            "uv": 1
          },
          {
            "time_epoch": 1643011200,
            "time": "2022-01-24 08:00",
            "temp_c": 2.6,
            "temp_f": 36.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 14,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 2.6,
            "heatindex_f": 36.7,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 2
          },
          {
            "time_epoch": 1643014800,
            "time": "2022-01-24 09:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 96,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 7,
            "feelslike_c": 2.3,
            "feelslike_f": 36.1,
            "windchill_c": 2.3,
            "windchill_f": 36.1,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4,
            "gust_kph": 6.5,
            "uv": 2
          },
          {
            "time_epoch": 1643018400,
            "time": "2022-01-24 10:00",
            "temp_c": 4,
            "temp_f": 39.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 6,
            "feelslike_c": 3.6,
            "feelslike_f": 38.5,
            "windchill_c": 3.6,
            "windchill_f": 38.5,
            "heatindex_c": 4,
            "heatindex_f": 39.2,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 2
          },
          {
            "time_epoch": 1643022000,
            "time": "2022-01-24 11:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 1,
            "feelslike_c": 7.5,
            "feelslike_f": 45.5,
            "windchill_c": 7.5,
            "windchill_f": 45.5,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643025600,
            "time": "2022-01-24 12:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 70,
            "cloud": 0,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643029200,
            "time": "2022-01-24 13:00",
            "temp_c": 9.1,
            "temp_f": 48.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 0,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 9.1,
            "heatindex_f": 48.4,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 3
          },
          {
            "time_epoch": 1643032800,
            "time": "2022-01-24 14:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.1,
            "feelslike_f": 48.4,
            "windchill_c": 9.1,
            "windchill_f": 48.4,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.3,
            "dewpoint_f": 37.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 3
          },
          {
            "time_epoch": 1643036400,
            "time": "2022-01-24 15:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 0,
            "feelslike_c": 9.3,
            "feelslike_f": 48.7,
            "windchill_c": 9.3,
            "windchill_f": 48.7,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643040000,
            "time": "2022-01-24 16:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 81,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.5,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 0,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.1,
            "gust_kph": 5,
            "uv": 3
          },
          {
            "time_epoch": 1643043600,
            "time": "2022-01-24 17:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.51,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 0,
            "feelslike_c": 7.2,
            "feelslike_f": 45,
            "windchill_c": 7.2,
            "windchill_f": 45,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.6,
            "gust_kph": 5.8,
            "uv": 1
          },
          {
            "time_epoch": 1643047200,
            "time": "2022-01-24 18:00",
            "temp_c": 7.3,
            "temp_f": 45.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 91,
            "wind_dir": "E",
            "pressure_mb": 1033,
            "pressure_in": 30.52,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 0,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 7.3,
            "heatindex_f": 45.1,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643050800,
            "time": "2022-01-24 19:00",
            "temp_c": 6.9,
            "temp_f": 44.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 0,
            "feelslike_c": 6.1,
            "feelslike_f": 43,
            "windchill_c": 6.1,
            "windchill_f": 43,
            "heatindex_c": 6.9,
            "heatindex_f": 44.4,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1643054400,
            "time": "2022-01-24 20:00",
            "temp_c": 3.7,
            "temp_f": 38.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 83,
            "wind_dir": "E",
            "pressure_mb": 1034,
            "pressure_in": 30.53,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 5,
            "feelslike_c": 2.5,
            "feelslike_f": 36.5,
            "windchill_c": 2.5,
            "windchill_f": 36.5,
            "heatindex_c": 3.7,
            "heatindex_f": 38.7,
            "dewpoint_c": 1.8,
            "dewpoint_f": 35.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1643058000,
            "time": "2022-01-24 21:00",
            "temp_c": 3.4,
            "temp_f": 38.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 10,
            "feelslike_c": 2.2,
            "feelslike_f": 36,
            "windchill_c": 2.2,
            "windchill_f": 36,
            "heatindex_c": 3.4,
            "heatindex_f": 38.1,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 1
          },
          {
            "time_epoch": 1643061600,
            "time": "2022-01-24 22:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 92,
            "cloud": 15,
            "feelslike_c": 1.9,
            "feelslike_f": 35.4,
            "windchill_c": 1.9,
            "windchill_f": 35.4,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1
          },
          {
            "time_epoch": 1643065200,
            "time": "2022-01-24 23:00",
            "temp_c": 3,
            "temp_f": 37.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1035,
            "pressure_in": 30.55,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 93,
            "cloud": 19,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 3,
            "heatindex_f": 37.4,
            "dewpoint_c": 2,
            "dewpoint_f": 35.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          }
        ]
      }
    ]
  }
}

@Injectable({
  providedIn: 'root'
})
export class WeatherApiService {

  private _currentSubject = new ReplaySubject<ICurrentWeather>(1);

  get current$(): Observable<ICurrentWeather> {
    return this._currentSubject.asObservable();
  }

  private _dailyForecastSubject = new ReplaySubject<IFullDailyForecast[]>(1);

  get dailyForecast$(): Observable<IFullDailyForecast[]> {
    return this._dailyForecastSubject.asObservable();
  }
  
  constructor (private _http: HttpClient) { }
  
  updateCurrentWeather(location: string = DEFAULT_CITY_NAME) {

    const url = `${environment.base_weather_api_url}/current.json`;
    
    let params = new HttpParams();
    params = params.append('key', environment.weather_api_key);
    params = params.append('q', location);
    params = params.append('aqi', 'no');

    this._http.get<ICurrentWeatherApiResponse>(url, { params })
      .pipe(catchError(error => {throw error})) // TODO: display HttpErrors in a more user friendly way
      .subscribe(data => this._currentSubject.next(data.current));
  }

  updateDailyForecast(location: string = DEFAULT_CITY_NAME, days: number = 3) {

    const url = `${environment.base_weather_api_url}/forecast.json`;
    
    let params = new HttpParams();
    params = params.append('key', environment.weather_api_key);
    params = params.append('q', location);
    params = params.append('days', days);
    params = params.append('aqi', 'no');
    params = params.append('alerts', 'no');

    // this._http.get<IForecastApiResponse>(url, { params })
    of(response)
      .pipe(catchError(error => {throw error})) // TODO: display HttpErrors in a more user friendly way
      .subscribe(data => {
        this._currentSubject.next(data.current);
        data.forecast.forecastday
        this._dailyForecastSubject.next(data.forecast.forecastday);
      });
  }
}
